package bean;
// Generated 30/11/2023 10:16:28 by Hibernate Tools 4.3.1s


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DrfCompraProduto generated by hbm2java
 */
@Entity
@Table(name="drf_compra_produto"
    ,catalog="db_davi_elizeche"
)
public class DrfCompraProduto  implements java.io.Serializable {


     private int drfIdcompraProduto;
     private DrfCompra drfCompra;
     private DrfProduto drfProduto;
     private int drfQuantidade;
     private double drfValorUnitario;

    public DrfCompraProduto() {
    }

    public DrfCompraProduto(int drfIdcompraProduto, DrfCompra drfCompra, DrfProduto drfProduto, int drfQuantidade, double drfValorUnitario) {
       this.drfIdcompraProduto = drfIdcompraProduto;
       this.drfCompra = drfCompra;
       this.drfProduto = drfProduto;
       this.drfQuantidade = drfQuantidade;
       this.drfValorUnitario = drfValorUnitario;
    }
   
     @Id@GeneratedValue(strategy=IDENTITY)

    
    @Column(name="drf_idcompra_produto", unique=true, nullable=false)
    public int getDrfIdcompraProduto() {
        return this.drfIdcompraProduto;
    }
    
    public void setDrfIdcompraProduto(int drfIdcompraProduto) {
        this.drfIdcompraProduto = drfIdcompraProduto;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="drf_id_compra", nullable=false)
    public DrfCompra getDrfCompra() {
        return this.drfCompra;
    }
    
    public void setDrfCompra(DrfCompra drfCompra) {
        this.drfCompra = drfCompra;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="drf_id_produto", nullable=false)
    public DrfProduto getDrfProduto() {
        return this.drfProduto;
    }
    
    public void setDrfProduto(DrfProduto drfProduto) {
        this.drfProduto = drfProduto;
    }

    
    @Column(name="drf_quantidade", nullable=false, precision=10)
    public int getDrfQuantidade() {
        return this.drfQuantidade;
    }
    
    public void setDrfQuantidade(int drfQuantidade) {
        this.drfQuantidade = drfQuantidade;
    }

    
    @Column(name="drf_valor_unitario", nullable=false, precision=10)
    public double getDrfValorUnitario() {
        return this.drfValorUnitario;
    }
    
    public void setDrfValorUnitario(double drfValorUnitario) {
        this.drfValorUnitario = drfValorUnitario;
    }




}


