package bean;
// Generated 30/11/2023 10:16:28 by Hibernate Tools 4.3.1s


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DrfCompra generated by hbm2java
 */
@Entity
@Table(name="drf_compra"
    ,catalog="db_davi_elizeche"
)
public class DrfCompra  implements java.io.Serializable {


     private int drfIdcompra;
     private DrfFornecedor drfFornecedor;
     private DrfFuncionario drfFuncionario;
     private Date drfDataCompra;
     private double drfValorTotalCompra;
     private int drfFormaPagamento;
     private int drfStatusCompra;


    public DrfCompra() {
    }

	
    public DrfCompra(int drfIdcompra, DrfFornecedor drfFornecedor, DrfFuncionario drfFuncionario, Date drfDataCompra, double drfValorTotalCompra, int drfFormaPagamento, int drfStatusCompra) {
        this.drfIdcompra = drfIdcompra;
        this.drfFornecedor = drfFornecedor;
        this.drfFuncionario = drfFuncionario;
        this.drfDataCompra = drfDataCompra;
        this.drfValorTotalCompra = drfValorTotalCompra;
        this.drfFormaPagamento = drfFormaPagamento;
        this.drfStatusCompra = drfStatusCompra;
    }
   
   
     @Id 

    
    @Column(name="drf_idcompra", unique=true, nullable=false)
    public int getDrfIdcompra() {
        return this.drfIdcompra;
    }
    
    public void setDrfIdcompra(int drfIdcompra) {
        this.drfIdcompra = drfIdcompra;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="drf_id_fornecedor", nullable=false)
    public DrfFornecedor getDrfFornecedor() {
        return this.drfFornecedor;
    }
    
    public void setDrfFornecedor(DrfFornecedor drfFornecedor) {
        this.drfFornecedor = drfFornecedor;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="drf_id_funcionario", nullable=false)
    public DrfFuncionario getDrfFuncionario() {
        return this.drfFuncionario;
    }
    
    public void setDrfFuncionario(DrfFuncionario drfFuncionario) {
        this.drfFuncionario = drfFuncionario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="drf_data_compra", nullable=false, length=10)
    public Date getDrfDataCompra() {
        return this.drfDataCompra;
    }
    
    public void setDrfDataCompra(Date drfDataCompra) {
        this.drfDataCompra = drfDataCompra;
    }

    
    @Column(name="drf_valor_total_compra", nullable=false, precision=10)
    public double getDrfValorTotalCompra() {
        return this.drfValorTotalCompra;
    }
    
    public void setDrfValorTotalCompra(double drfValorTotalCompra) {
        this.drfValorTotalCompra = drfValorTotalCompra;
    }

    
    @Column(name="drf_forma_pagamento", nullable=false)
    public int getDrfFormaPagamento() {
        return this.drfFormaPagamento;
    }
    
    public void setDrfFormaPagamento(int drfFormaPagamento) {
        this.drfFormaPagamento = drfFormaPagamento;
    }

    
    @Column(name="drf_status_compra", nullable=false)
    public int getDrfStatusCompra() {
        return this.drfStatusCompra;
    }
    
    public void setDrfStatusCompra(int drfStatusCompra) {
        this.drfStatusCompra = drfStatusCompra;
    }





}


