package bean;
// Generated 22/09/2023 15:22:46 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DrfProduto generated by hbm2java
 */
@Entity
@Table(name="drf_produto"
    ,catalog="db_davi_elizeche"
)
public class DrfProduto  implements java.io.Serializable {


     private int drfIdProduto;
     private double drfValorUnitario;
     private String drfCategoria;
     private String drfDescricao;
     private String drfColecao;


    public DrfProduto() {
    }

	
    public DrfProduto(int drfIdProduto, float drfValorUnitario, String drfCategoria, String drfDescricao, String drfColecao) {
        this.drfIdProduto = drfIdProduto;
        this.drfValorUnitario = drfValorUnitario;
        this.drfCategoria = drfCategoria;
        this.drfDescricao = drfDescricao;
        this.drfColecao = drfColecao;
    }
    
   
     @Id 

    
    @Column(name="drf_idProduto", unique=true, nullable=false)
    public int getDrfIdProduto() {
        return this.drfIdProduto;
    }
    
    public void setDrfIdProduto(int drfIdProduto) {
        this.drfIdProduto = drfIdProduto;
    }

    
    @Column(name="drf_valor_unitario", nullable=false, precision=12, scale=0)
    public double getDrfValorUnitario() {
        return this.drfValorUnitario;
    }
    
    public void setDrfValorUnitario(double drfValorUnitario) {
        this.drfValorUnitario = drfValorUnitario;
    }

    
    @Column(name="drf_categoria", nullable=false, length=50)
    public String getDrfCategoria() {
        return this.drfCategoria;
    }
    
    public void setDrfCategoria(String drfCategoria) {
        this.drfCategoria = drfCategoria;
    }

    
    @Column(name="drf_descricao", nullable=false, length=60)
    public String getDrfDescricao() {
        return this.drfDescricao;
    }
    
    public void setDrfDescricao(String drfDescricao) {
        this.drfDescricao = drfDescricao;
    }

    
    @Column(name="drf_colecao", nullable=false, length=25)
    public String getDrfColecao() {
        return this.drfColecao;
    }
    
    public void setDrfColecao(String drfColecao) {
        this.drfColecao = drfColecao;
    }






}


