/*s
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.DrfCompras_DAO;
import bean.DrfFuncionario;
import dao.DrfFuncionario_DAO;
import bean.DrfFornecedor;
import dao.DrfFornecedor_DAO;

import bean.DrfCompra;
import bean.DrfCompraProduto;
import dao.DrfCompraProduto_DAO;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import tools.Util;

/**
 *
 * @author rafae
 */
public class JDlgDrfCompras extends javax.swing.JDialog {

    public DrfCompra compra;
    public DrfCompras_DAO drfCompras_DAO;
    public DrfFornecedor_DAO fornecedor_DAO;
    public DrfFornecedor fornecedor;
    public DrfCompraProduto_DAO comprasProduto_DAO;
    public DrfCompraProduto comprasProduto;
    public JDlgDrfCompraProduto jDlgDrfCompraProduto;
    public CompraProdutoControle compraProdutoControle;
    MaskFormatter mascaraData;
    private boolean incluindo;

    public JDlgDrfCompras(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
            setTitle("Compras");
        Util.habilitar(false, jBtnConfirmar, jBtnCancelar, jTxtCodigo, jCboFornecedor, jFmtData, jCboFuncionario, jCboFormaPagamento, jCboStatus, jTxtTotal, jBtnAlterarProd, jBtnIncluirProd, jBtbExcluirProd);
        Util.habilitar(true, jBtnExcluir, jBtnIncluir, jBtnAlterar, jBtnPesquisar);

        try {
            mascaraData = new MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            Logger.getLogger(JDlgDrfCompras.class.getName()).log(Level.SEVERE, null, ex);
        }

        jFmtData.setFormatterFactory(new DefaultFormatterFactory(mascaraData));

        compra = new DrfCompra();
        drfCompras_DAO = new DrfCompras_DAO();
        
        comprasProduto_DAO = new DrfCompraProduto_DAO();
        List lista = new ArrayList();
        compraProdutoControle = new CompraProdutoControle();
        compraProdutoControle.setList(lista);
        jTable1.setModel(compraProdutoControle);

        fornecedor_DAO = new DrfFornecedor_DAO();
        List listaFornecedor = fornecedor_DAO.listAll();
        for (int i = 0; i < listaFornecedor.size(); i++) {
            fornecedor = (DrfFornecedor) listaFornecedor.get(i);
            jCboFornecedor.addItem(fornecedor);
        }

        DrfFuncionario_DAO funcionario_DAO = new DrfFuncionario_DAO();
        List listaFuncionario = funcionario_DAO.listAll();
        for (int i = 0; i < listaFuncionario.size(); i++) {
            DrfFuncionario funcionario = (DrfFuncionario) listaFuncionario.get(i);
            jCboFuncionario.addItem(funcionario);
        }
    }

    public DrfCompra viewBean() {

        compra = new DrfCompra();

        compra.setDrfIdcompra(Util.strInt(jTxtCodigo.getText()));

        compra.setDrfFornecedor((DrfFornecedor) jCboFornecedor.getSelectedItem());
        compra.setDrfFuncionario((DrfFuncionario) jCboFuncionario.getSelectedItem());
        compra.setDrfDataCompra(Util.strDate(jFmtData.getText()));
        compra.setDrfValorTotalCompra(Util.strDouble(jTxtTotal.getText()));
        compra.setDrfFormaPagamento(jCboFormaPagamento.getSelectedIndex());
        compra.setDrfStatusCompra(jCboStatus.getSelectedIndex());

        return compra;

    }

    public void beanView(DrfCompra compra) {

        jTxtCodigo.setText(Util.intStr(compra.getDrfIdcompra()));
        jCboFornecedor.setSelectedItem(compra.getDrfFornecedor());
        jCboFuncionario.setSelectedItem((compra.getDrfFuncionario()));

        jFmtData.setText(Util.datestr(compra.getDrfDataCompra()));
        jCboFormaPagamento.setSelectedIndex(compra.getDrfFormaPagamento());
        jCboStatus.setSelectedIndex(compra.getDrfStatusCompra());
        jTxtTotal.setText(Util.doubleStr(compra.getDrfValorTotalCompra()));

        comprasProduto_DAO = new DrfCompraProduto_DAO();
        List listaProdutos = (List) comprasProduto_DAO.listProdutos(compra);

        compraProdutoControle.setList(listaProdutos);

    }

    public int getSelectedRowProd() {
        return jTable1.getSelectedRow();
    }

       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCboFornecedor = new javax.swing.JComboBox<DrfFornecedor>();
        jBtbExcluirProd = new javax.swing.JButton();
        jCboFuncionario = new javax.swing.JComboBox<DrfFuncionario>();
        jLabel6 = new javax.swing.JLabel();
        jTxtTotal = new javax.swing.JTextField();
        jCboFormaPagamento = new javax.swing.JComboBox<>();
        jBtnPesquisar = new javax.swing.JButton();
        jCboStatus = new javax.swing.JComboBox<>();
        jBtnIncluir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jBtnExcluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnConfirmar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTxtCodigo = new javax.swing.JTextField();
        jBtnIncluirProd = new javax.swing.JButton();
        jFmtData = new javax.swing.JFormattedTextField();
        jBtnAlterarProd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jCboFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboFornecedorActionPerformed(evt);
            }
        });

        jBtbExcluirProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtbExcluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtbExcluirProdActionPerformed(evt);
            }
        });

        jLabel6.setText("Forma Pagamento");

        jCboFormaPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cartão", "Pix" }));

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jCboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Concluida", "Em andamento", "Cancelada" }));

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jLabel7.setText("Status");

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar.png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jLabel1.setText("Num Compra");

        jLabel2.setText("Data");

        jLabel3.setText("Fornecedor");

        jLabel4.setText("Funcionario");

        jLabel5.setText("Total");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "PRODUTO", "QUANTIDADE", "VALOR UNITARIO", "TOTAL"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jBtnIncluirProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnIncluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirProdActionPerformed(evt);
            }
        });

        jBtnAlterarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnAlterarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jFmtData, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCboFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(70, 70, 70)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jCboFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jBtnIncluirProd, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jBtbExcluirProd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jBtnAlterarProd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnCancelar)
                        .addGap(14, 14, 14)
                        .addComponent(jBtnPesquisar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCboFormaPagamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jCboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCboFornecedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFmtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCboFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnIncluirProd, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jBtnAlterarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jBtbExcluirProd, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnCancelar)
                        .addComponent(jBtnPesquisar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnIncluir)
                        .addComponent(jBtnExcluir)
                        .addComponent(jBtnAlterar)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCboFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboFornecedorActionPerformed

    private void jBtbExcluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtbExcluirProdActionPerformed
        if (getSelectedRowProd() == -1) {
            Util.mensagem("Nenhuma linha selecionada");
        } else {
            if (Util.perguntar("ConfirmarExclusão do produto") == true) {
                compraProdutoControle.removeBean(getSelectedRowProd());
            }
        }
       
    }//GEN-LAST:event_jBtbExcluirProdActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        JDlgDrfCompraPesquisa jDlgDrfCompraPesquisa = new JDlgDrfCompraPesquisa(null, true);
        jDlgDrfCompraPesquisa.setTelaAnterior(this);
        jDlgDrfCompraPesquisa.setVisible(true);
           
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        Util.habilitar(true, jTxtCodigo, jCboFornecedor, jFmtData, jCboFuncionario, jCboFormaPagamento, jCboStatus, jTxtTotal, jBtnConfirmar, jBtnCancelar, jBtnAlterarProd, jBtnIncluirProd, jBtbExcluirProd, jTable1);
        Util.habilitar(false, jBtnExcluir, jBtnIncluir, jBtnAlterar, jBtnPesquisar); // TODO add your handling code here:

        Util.limparCampos(jTxtCodigo, jFmtData, jCboFornecedor, jCboFuncionario, jTxtTotal, jCboFormaPagamento, jCboStatus);

        compraProdutoControle.setList(new ArrayList());
        jTxtCodigo.grabFocus();
        incluindo = true;
        compra = new DrfCompra();
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        if (compra != null) {
            if (Util.perguntar("Deseja excluir a Compra ?") == true) {
                comprasProduto_DAO = new DrfCompraProduto_DAO();
                DrfCompraProduto compraProduto;
                for (int linha = 0; linha < jTable1.getRowCount(); linha++) {
                    compraProduto = compraProdutoControle.getBean(linha);
                    comprasProduto_DAO.delete(compraProduto);
                }
                comprasProduto_DAO.delete(compra);
               
            }
        } else {
            Util.mensagem("Deve ser realizada uma pesquisa antes");
        }
Util.limparCampos(jTxtCodigo, jCboFornecedor, jFmtData, jCboFuncionario, jCboFormaPagamento, jCboStatus, jTxtTotal, jTable1);
            compraProdutoControle.setList(new ArrayList());                                                                                                                  
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed

        Util.habilitar(false, jBtnExcluir, jBtnIncluir, jBtnAlterar, jBtnPesquisar);

        if (compra != null) {
            
           comprasProduto_DAO = new DrfCompraProduto_DAO();
                DrfCompraProduto compraProduto;
                for (int linha = 0; linha < jTable1.getRowCount(); linha++) {
                    compraProduto = compraProdutoControle.getBean(linha);
                    comprasProduto_DAO.delete(compraProduto);}
                
                
         
            
        } else {
            Util.mensagem("Deve ser realizada uma pesquisa antes");
        }
incluindo = false;
   Util.habilitar(true, jTxtCodigo, jCboFornecedor, jFmtData, jCboFuncionario, jCboFormaPagamento, jCboStatus, jTxtTotal, jBtnConfirmar, jBtnCancelar, jBtnAlterarProd, jBtnIncluirProd, jBtbExcluirProd, jTable1);
   Util.habilitar(false, jBtnIncluir, jBtnAlterar, jBtnExcluir, jBtnPesquisar);
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        compraProdutoControle.setList(new ArrayList());
        Util.habilitar(false, jTxtCodigo, jCboFornecedor, jFmtData, jCboFuncionario, jCboFormaPagamento, jCboStatus, jTxtTotal, jBtnConfirmar, jBtnCancelar,jBtnExcluir,jBtnAlterar, jBtnAlterarProd, jBtnIncluirProd, jBtbExcluirProd);
        Util.habilitar(true, jBtnIncluir, jBtnPesquisar);
        Util.limparCampos(jTxtCodigo, jCboFornecedor, jFmtData, jCboFuncionario, jCboFormaPagamento, jCboStatus, jTxtTotal, jTable1);
       
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        compra = viewBean();
 drfCompras_DAO = new DrfCompras_DAO();
        
        if (incluindo == true) {
            drfCompras_DAO.insert(compra);
            comprasProduto_DAO = new DrfCompraProduto_DAO();
            DrfCompraProduto compraProduto;
            for (int linha = 0; linha < jTable1.getRowCount(); linha++) {
                compraProduto = compraProdutoControle.getBean(linha);
                compraProduto.setDrfCompra(compra);
                comprasProduto_DAO.insert(compraProduto);

            }

        } else {
            drfCompras_DAO.update(compra);
            comprasProduto_DAO = new DrfCompraProduto_DAO();
            DrfCompraProduto compraProduto;
            for (int linha = 0; linha < jTable1.getRowCount(); linha++) {
                compraProduto = compraProdutoControle.getBean(linha);
                compraProduto.setDrfCompra(compra);
                comprasProduto_DAO.insert(compraProduto);
            }
       Util.habilitar(true, jBtnIncluir, jBtnPesquisar);
            Util.habilitar(false, jBtnExcluir, jBtnAlterar, jTxtCodigo, jCboFornecedor, jFmtData, jCboFuncionario, jCboFormaPagamento, jCboStatus, jTxtTotal, jTable1);
            Util.limparCampos(jTxtCodigo, jCboFornecedor, jFmtData, jCboFuncionario, jCboFormaPagamento, jCboStatus, jTxtTotal, jTable1);
             compraProdutoControle.setList(new ArrayList());
        }
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnIncluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirProdActionPerformed
        jDlgDrfCompraProduto = new JDlgDrfCompraProduto(null, true);
        jDlgDrfCompraProduto.setTitle("Inclusão de produtos");
        jDlgDrfCompraProduto.setTelaAnterior(this);
        jDlgDrfCompraProduto.setVisible(true);
    }//GEN-LAST:event_jBtnIncluirProdActionPerformed

    private void jBtnAlterarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarProdActionPerformed
        jDlgDrfCompraProduto = new JDlgDrfCompraProduto(null, true);
        jDlgDrfCompraProduto.setTitle("Alteração de produtos");
        jDlgDrfCompraProduto.setTelaAnterior(this);
        int linSel = jTable1.getSelectedRow();
        DrfCompraProduto compraProduto = (DrfCompraProduto) compraProdutoControle.getBean(linSel);
        jDlgDrfCompraProduto.beanView(compraProduto);
        jDlgDrfCompraProduto.setVisible(true);
    }//GEN-LAST:event_jBtnAlterarProdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgDrfCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgDrfCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgDrfCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgDrfCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgDrfCompras dialog = new JDlgDrfCompras(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtbExcluirProd;
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnAlterarProd;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnIncluirProd;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JComboBox<String> jCboFormaPagamento;
    private javax.swing.JComboBox<DrfFornecedor> jCboFornecedor;
    private javax.swing.JComboBox<DrfFuncionario> jCboFuncionario;
    private javax.swing.JComboBox<String> jCboStatus;
    private javax.swing.JFormattedTextField jFmtData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTxtCodigo;
    private javax.swing.JTextField jTxtTotal;
    // End of variables declaration//GEN-END:variables
}
